name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-
      - name: Install
        run: npm install
      - name: Lint check
        run: npm run fmt-check
  integration-tests:
    strategy:
      matrix:
        dialect: [ mysql, postgres, sqlite ]
        language: [ ts, js ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-
      - name: Install
        run: npm install
      - name: Build Typescript Files
        run: npm run build
      - uses: ariga/setup-atlas@master
      - name: Run Test as Standalone
        # TODO: remove this when we have a standalone binary for js
        if: ${{ matrix.language != 'js' }}
        working-directory: ./testdata/${{ matrix.language }}
        run: |
          atlas migrate diff --env typeorm -c "file://atlas-standalone.hcl" --var dialect=${{ matrix.dialect }}
      - name: Verify migrations generated
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo "you need to run 'atlas migrate diff --env typeorm' and commit the changes"
            echo "$status"
            git --no-pager diff
            exit 1
           fi
      - name: Run Test as ${{ matrix.language }} Script
        working-directory: ./testdata/${{ matrix.language }}
        run: |
          atlas migrate diff --env typeorm -c "file://atlas-script.hcl" --var dialect=${{ matrix.dialect }}
      - name: Verify migrations generated
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo "you need to run 'atlas migrate diff --env typeorm' and commit the changes"
            echo "$status"
            git --no-pager diff
            exit 1
           fi
